# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 21:25
from __future__ import unicode_literals
from tenant_users.compat import TENANT_SCHEMAS
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_owner'),
    ]

    if not TENANT_SCHEMAS:
        operations = [
            migrations.RemoveField(
                model_name='client',
                name='domain_url',
            ),
            migrations.CreateModel(
                name='Domain',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                    ('is_primary', models.BooleanField(default=True)),
                    ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains',
                                                 to='customers.Client')),
                ],
                options={
                    'abstract': False,
                },
            ),
        ]
