PUBLIC_ROLE_DEFAULT = 'Public Default'

COMPANY_ROLE_ADMIN = 'Admin'

PUBLIC_TENANT_DEFAULT_ROLES = {
    PUBLIC_ROLE_DEFAULT : [
    ],
}

COMPANY_TENANT_DEFAULT_ROLES = {
    COMPANY_ROLE_ADMIN : [
    ],
}
